alkemyTech/OT-96-Server

helpers/sendWelcomeEmail.js, views/welcomeEmail.ejs
* Welcome Email template
* Send Welcome Email Helper
=> Welcome email template/ot96 132

app.js, controllers/authentications.js, package.json, services/authentications.js, services/users.js
=> Ot96 127 bugfix

services/security.js
- change property userForToken
- user > id
=> refactor security.js

helpers/sendWelcomeEmail.js
line 8: 
const organization = organizationsController.getById(organizationId); => const organization = organizationsService.getById(organizationId);
=> refactoring helpers/sendWelcomeEmail.js

migrations/20211027170548-create-testimonial.js, seeders/20211029220548-create-demo-testimonials.js
=> Testimonials seeders

middlewares/auths.js
* Refactoring middlewares/auths.js
=> refactoring middlewares/auths.js

services/emailSender.js
=> OT96-130/refactor

seeders/20211026234248-create-demo-categories.js, seeders/20211029220548-create-demo-testimonials.js
el nombre de la tabla estaba mal escrito, lo que lanzaba un error a la hora de usar los seeder en sequelize-cli
=> bugs fixed in migration, in the 'seeders' part

middlewares/auths.js
- fix isAdmin and isOwnership roles
=> fix middlewares/auths.js

controllers/users.js, middlewares/auths.js, routes/users.js, services/users.js
- Endpoint getAll users
- Controller getAll
- errorHandler in service
=> Ot96 138/listado usuarios

app.js, controllers/news.js, middlewares/newsDataValidation.js, migrations/20211026140438-create-news.js, models/news.js, repositories/news.js, routes/news.js, seeders/20211026234249-create-demo-news.js, services/news.js
-implementación de Endpoint '/news' para creacion.
- creacion de middleware de validación de datos de news.
- creacion de ruta + aplicación en app.js de la ruta News
=> Ot96 149/ endpoint create news

controllers/categories.js, middlewares/auths.js, middlewares/userValidation.js, repositories/activities.js, repositories/categories.js, repositories/organizations.js, repositories/slides.js, repositories/testimonials.js, routes/categories.js, routes/index.js, routes/users.js, services/categories.js, services/organizations.js, services/slides.js, services/users.js
-  Creacion de endpoint (/categories/:id) para update.
- Utilización de verificador de token y administrador en ruta
=> Ot96 146/endpoint update category

.env.example, services/emailSender.js
- Cambio de cuenta y Api Key de Sendgrid
=> Sendgrin implementation

seeders/20211026234250-create-demo-activities.js
=> add seeder activities

controllers/users.js
se modifico el endpoint register para que al registrarte te devuelva el token creado
=> Se agrego token en registro

routes/news.js
=> bug fixed in news route

controllers/activities.js, controllers/categories.js, controllers/news.js, controllers/slides.js, controllers/users.js, services/images.js
creacion de servicios image y intergracion
=> Ot96 142 v2

repositories/organizations.js, routes/categories.js, routes/organization.js
=> Fixes before demo

controllers/authentications.js, routes/authentications.js, routes/categories.js, services/security.js
#Endpoint datos usuario autenticado
* auth/me route
* controllers/authentications.myData function
=> Ot96 139/endpoint auth me

models/news.js
=>  fix alias in model category

app.js
=> add slides routes & eliminate extra category

middlewares/auths.js, models/news.js, routes/activities.js, routes/categories.js, routes/news.js, routes/slides.js, routes/users.js
=> Refactor demo

repositories/activities.js, repositories/categories.js, repositories/contacts.js, repositories/members.js, repositories/news.js, repositories/organizations.js, repositories/roles.js, repositories/slides.js, repositories/testimonials.js, repositories/users.js
=> refactor repositories

controllers/activities.js, controllers/authentications.js, controllers/categories.js, controllers/contacts.js, controllers/members.js, controllers/news.js, controllers/organization.js, controllers/roles.js, controllers/slides.js, controllers/testimonials.js, controllers/users.js, routes/authentications.js, routes/categories.js, routes/index.js, routes/news.js, routes/organization.js, routes/slides.js, routes/users.js
-Refactorización de controllers,.
-Corrección de los Router.
=> Controller refactor

app.js, controllers/contacts.js, middlewares/contacts.js, routes/contacts.js, services/contacts.js
-Creacion de Endpoint Create Contacts
-Creacion de Middleware de validación de campos (name y email)
=> Ot96 158/create contacts

services/slides.js
prácticamente ya estaba echo la parte de update, solo le agregue algunas mejoras
=> code improvements

app.js, controllers/members.js, repositories/members.js, routes/members.js, services/members.js
-Creacion de Endpoint getAll members.
- utilización de middleware para validación de ADMIN
=> Ot96 175/get all members

Somos Mas.postman_collection.json, app.js, controllers/testimonials.js, repositories/testimonials.js, routes/testimonials.js, services/testimonials.js
-Creacion de endpoint Update Testimonials
-agregado de endpoints en archivo postman (testimonials, contacts & members)
=> Ot96 172/update testimonials

controllers/members.js, middlewares/members.js, repositories/members.js, routes/members.js, services/members.js
- Add member create repository
- Add member create service
- Add member create controller
- Add member create route
- Add member middleware
=> Ot96 176 - Endpoint Creación miembros

controllers/comments.js, migrations/20211110232306-create-comment.js, models/comment.js, models/news.js, models/user.js, repositories/comments.js, services/comments.js
-Creacion de Modelo y migración de Comments
-Creacion de los archivos Controllers, Service & reposiroty de Comments (en blanco)
=> Ot96 181/model comments

migrations/20211026034629-create-organization.js, models/organization.js, seeders/20211029220548-create-demo-organizations.js
- adding contact fields in organizations
- models
- migrations
- seeders
=> adding contact fields in organizations

Somos Mas.postman_collection.json, middlewares/testimonials.js, routes/testimonials.js
* POST /testimonials route
* Middleware validations
* Postman Endpoint documentation
=> Ot96 171/endpoint create testimonial

repositories/organizations.js
Agregue la la relacion en la ruta get para que se muestre, no la pude probar porque tdv no estaba el modelo creado
=> se incluyo la relacion Slide a la ruta publica

controllers/slides.js, migrations/20211029201240-create-slide.js, models/slide.js, services/aws_s3.js, services/imageUploader.js, services/slides.js
creación de endpoint createSlide con conexión a aws
=> Ot96 161/creacion slides

controllers/members.js, controllers/organization.js, controllers/slides.js, controllers/testimonials.js, controllers/users.js, repositories/testimonials.js, services/categories.js, services/slides.js, services/testimonials.js
Corrección de las respuestas de endpoint.
=> Refactor respuestas endpoint

middlewares/activities.js, middlewares/categories.js, middlewares/contacts.js, middlewares/members.js, middlewares/news.js, middlewares/organizations.js, middlewares/testimonials.js
isAlphaNumeric causa que no se pueda insertar espacios en los campos de nombre
isAlpha(str [, locale, options]) = check if the string contains only letters and numbers (a-zA-Z0-9)
=> alphaNumeric() to alpha()

app.js, package.json, swaggerDefinition.json
adding swagger documentation
- app.js
- package.json
- swaggerDefinition.json
=> adding swagger documentation

routes/authentications.js, swaggerDefinition.json
- Configuration in swagger json
- Documentation in authentication
=> Ot96 196/documentation autentication

app.js
- Custom and simple error handler
=> add custom error handler

middlewares/auths.js
el atributo userId no existe, en ves de eso existe UserId.
=> bug fixed in comment.

routes/testimonials.js
- Added documentation to testimonials
=> Testimonials documentation

migrations/20211026104152-create-members.js, models/member.js, routes/members.js
* Members Swagger documentation
* Members description fix
=> Ot96 194/members documentation

routes/categories.js
=> category documentation

repositories/members.js, routes/members.js, routes/news.js, routes/testimonials.js, services/members.js
- refactor general
- comentarios funcionando
=> General refactor

repositories/news.js, routes/categories.js, routes/members.js, routes/news.js, routes/testimonials.js
=> refactor: demo funcionando 1.0

controllers/members.js, repositories/members.js, routes/members.js, services/members.js
* Pagination
* Route permissions
* Delete
=> Post refactor

controllers/authentications.js
- Login structure improve & standarization
=> login refactor
